version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: 'postgres'
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
